# Parse all files with TypeScript.
extends:
  - 'standard-with-typescript'
  - 'prettier'
  - 'plugin:typescript-enum/recommended'
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'

parser: '@typescript-eslint/parser'

parserOptions:
  project: './tsconfig.json'
  createDefaultProgram: true

plugins:
  - prettier
  - react
  - jest
  - jest-dom
  - '@typescript-eslint'
  - react-hooks
  - typescript-enum

settings:
  react:
    version: detect

env:
  browser: true

rules:
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: error

  no-unused-vars: 0
  '@typescript-eslint/no-unused-vars':
    - error
    - varsIgnorePattern: _
      argsIgnorePattern: _

  no-labels: [error, {allowLoop: true}]
  no-void: 0
  '@typescript-eslint/member-delimiter-style':
    - error
    - singleline:
        delimiter: 'semi'
        requireLast: false
  ban-ts-comment: 0
  '@typescript-eslint/ban-ts-comment': 0
